### ISSUE TITLE
Error "cannot find symbol" in ViewListener.java:49 preventing the jitpack to build.

### ISSUE THREAD

**Issue by stooneg0mes** [SaiintBrisson/inventory-framework#10]
![image](https://user-images.githubusercontent.com/53417375/111893812-16066a00-89e4-11eb-9b11-4cd7b85d7459.png)

### How to fix it?
Import "org.bukkit.event.inventory.InventoryDragEvent" on ViewListener.java

**Comment by eokasta** [comment]
nerd?
